# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
#  'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Reproducibility for Everyone"
email: "repro4everyone@gmail.com"
description: "Resources to support reproducible research"
keywords: "reproducibility, reproducible research, open science"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://repro4every.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com
cover_image: "https://themeix.com/wp-content/uploads/dooxy-responsive-html-template-preview.png"
## Theme Options
animated_header: "true"
twitter_username: repro4everyone
github_username:  repro4everyone




# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


# Tag Options
tag_page_layout: tag_page
tag_page_dir: tag

permalink: /:title/ 
 
collections:
  team_members:
    output: true
    permalink: /team_members/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/
  docs:
    output: true
    permalink: /docs/:path/



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/  d
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
